<?php

require_once drupal_get_path('module', 'myapi') . '/inc/menu.inc';
require_once drupal_get_path('module', 'myapi') . '/inc/node.inc';

/**
 * Implementation of hook_menu
 */
function myapi_menu () {
  $items['api'] = array(
    'title' => 'Menu',
    'description' => 'My Drupal Api',
    'page callback' => 'apiRouter',
    //'page callback' => 'testFunction',
    'access arguments' => array('access content')
  );

  return $items;
}

function testFunction ($arg, $arg2='none', $arg3='none') {
  print $arg . ' is the argument passed<br>';
  print $arg2 . ' is the second argument passed<br>';
  print $arg3 . ' is the third argument passed<br>';
}

/**
 * Callback functions for api/
 */
function apiRouter ($type, $id, $page=0) {

  //set header to json
  header('Content-Type: application/json');

  switch ($type) {
    /*
    @request a menu
    */
    case 'menu':
      getMenu($id);
      break;

    /*
    @request a block
    */
    case 'block':
      break;

    /*
    @request a page
    */
    case 'page':
      getPage($id);
      break;


    /*
    @request a node
    */
    case 'node':
      getNode($id);
      break;


    /*
    DEFAULT
    */
    default:
      break;
  }

}



/**
 * Returns?
 *
 * @Resource URL
 * /api/page/ [sample: /api/page/1]
 *
 * @param $id
 * ID for the page
 */
function getPage($id) {
  // $type = node_type_load('page');
  // print json_encode($type);
  $g = $_GET;

  //print_r($g);

  $node = getNode($id, TRUE);
  $menu = getMenu('main-menu', TRUE);

  $output = array(
    'querie' => $g['q'],
    'node' => $node,
    'menu' => $menu
  );

  echo json_encode($output);

}



