<?php

require_once drupal_get_path('module', 'myapi') . '/inc/menu.inc';
require_once drupal_get_path('module', 'myapi') . '/inc/node.inc';

/**
 * Implementation of hook_menu
 */
function myapi_menu () {
  $items['api'] = array(
    'title' => 'Menu',
    'description' => 'My Drupal Api',
    'page callback' => 'apiRouter',
    //'page callback' => 'testFunction',
    'access arguments' => array('access content')
  );

  return $items;
}

function testFunction ($arg, $arg2='none', $arg3='none') {
  print $arg . ' is the argument passed<br>';
  print $arg2 . ' is the second argument passed<br>';
  print $arg3 . ' is the third argument passed<br>';
}

/**
 * Callback functions for api/
 */
function apiRouter ($type, $id, $page=0) {

  //set header to json
  header('Content-Type: application/json');

  switch ($type) {
    /*
    @request a menu
    */
    case 'menu':
      getMenu($id);
      break;

    /*
    @request a block
    */
    case 'block':
      break;

    /*
    @request a page
    */
    case 'page':
      getPage($id);
      break;


    /*
    @request a node
    */
    case 'node':
      getNode($id);
      break;

    /*
    @request a view
    */
    case 'view':
      getView($id);
      break;


    /*
    DEFAULT
    */
    default:
      break;
  }

}



/**
 * Returns?
 *
 * @Resource URL
 * /api/page/ [sample: /api/page/1]
 *
 * @param $id
 * ID for the page
 */
function getPage($id) {
  // $type = node_type_load('page');
  // print json_encode($type);
  $g = $_GET;
  // foreach ($g as $k => $v) {
  //   print("{$k} is {$v} -- AND -- ");
  // }
  //print_r($g);

  $node = getNode($id, TRUE);
  $menu = getMenu('main-menu', TRUE);

  $output = array(
    'querie' => $g['q'],
    'node' => $node,
    'menu' => $menu
  );

  if ($_GET['view']) {
    $view_name = $_GET['view'];
    $output['view'] = getView($view_name, 0, TRUE);
  }



  echo json_encode($output);

}



/**
 * Returns?
 *
 * @Resource URL
 * /api/page/ [sample: /api/page/1]
 *
 * @param $id
 * ID for the page
 */
function getView($name, $page=0, $internal=FALSE) {
  $view = views_get_view($name);

  $view->init_display();
  $view->current_page = $page;

  $view->pre_execute();
  $view->execute();
  $view_result = $view->result;

  $rows = array();
  foreach ($view_result as $row) {
    $rows[$row->nid] = $row;
  }

  if ($internal === TRUE) {
    return $rows;
  } else {
    echo json_encode($rows);
  }





}




