<?php

require_once drupal_get_path('module', 'myapi') . '/inc/menu.inc';
require_once drupal_get_path('module', 'myapi') . '/inc/node.inc';
require_once drupal_get_path('module', 'myapi') . '/inc/view.inc';

/**
 * Implementation of hook_menu
 */
function myapi_menu () {
  $items['api'] = array(
    'title' => 'Menu',
    'description' => 'My Drupal Api',
    'page callback' => 'apiRouter',
    //'page callback' => 'testFunction',
    'access arguments' => array('access content')
  );

  return $items;
}

function testFunction ($arg, $arg2='none', $arg3='none') {
  print $arg . ' is the argument passed<br>';
  print $arg2 . ' is the second argument passed<br>';
  print $arg3 . ' is the third argument passed<br>';
}

/**
 * Callback functions for api/
 */
function apiRouter ($type, $id, $page=0) {

  //set header to json
  header('Content-Type: application/json');

  switch ($type) {
    /*
    @request a menu
    */
    case 'menu':
      $menu = getMenu($id);
      echo json_encode($menu);
      break;

    /*
    @request a block
    */
    case 'block':
      break;

    /*
    @request a page
    */
    case 'page':
      $page = getPage($id);
      echo json_encode($page);
      break;

    /*
    @request a node
    */
    case 'node':
      $node = getNode($id);
      echo json_encode($node);
      break;

    /*
    @request a view
    */
    case 'view':
      $view = getView($id);
      echo json_encode($view);
      break;


    /*
    DEFAULT
    */
    default:
      break;
  }

}



/**
 * Returns?
 *
 * @Resource URL
 * /api/page/ [sample: /api/page/1]
 *
 * @param $id
 * ID for the page
 */
function getPage($id) {
  // $type = node_type_load('page');
  // print json_encode($type);
  $g = $_GET;
  // foreach ($g as $k => $v) {
  //   print("{$k} is {$v} -- AND -- ");
  // }
  //print_r($g);

  $node = getNode($id);
  $menu = getMenu('main-menu');

  $output = array(
    'querie' => $g['q'],
    'node' => $node,
    'menu' => $menu
  );

  if ($_GET['view']) {
    $view_name = $_GET['view'];
    $output['view'] = getView($view_name);
  }

  return $output;

}




